#!/usr/bin/env python3
"""Download the 151 Kanto sprites and write them out as base64 data URIs.

The pack opener draws each card face to a 2D canvas that THREE uploads as a
WebGL texture, so every sprite must be CORS-clean or the upload throws
SecurityError. Bundling sidesteps the question entirely: a data: URI never
taints the canvas and needs no network at runtime.

    python3 bundle-sprites.py                      # sprites-data.js (default art)
    python3 bundle-sprites.py --gen1               # Red/Blue sprites
    python3 bundle-sprites.py --gen1 --inline kanto-pack-opener.html

--inline additionally writes a single self-contained HTML file with the sprite
data spliced in, so the result works from file:// with no sibling assets.
"""

import argparse
import base64
import concurrent.futures as futures
import json
import pathlib
import re
import sys
import urllib.error
import urllib.request

COUNT = 151

# Keyed by National Dex number, so no per-name filename mapping is needed for
# Nidoran-f/m, Farfetch'd or Mr. Mime.
PATHS = {
    "default": "sprites/pokemon",
    "gen1": "sprites/pokemon/versions/generation-i/red-blue/transparent",
}

# jsdelivr first: the page already loads three.js from it, so it is known
# reachable wherever the opener runs.
HOSTS = (
    "https://cdn.jsdelivr.net/gh/PokeAPI/sprites@master/{path}/{id}.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/{path}/{id}.png",
    "https://cdn.statically.io/gh/PokeAPI/sprites/master/{path}/{id}.png",
)

# Matches the sprites-data.js tag whether or not it is still commented out.
MARKER = re.compile(r'(?:<!--\s*)?<script src="sprites-data\.js"></script>(?:\s*-->)?')


def fetch(dex_id, path, timeout):
    """Return PNG bytes for one dex number, trying each host in turn."""
    last = None
    for host in HOSTS:
        url = host.format(path=path, id=dex_id)
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "bundle-sprites/1.0"})
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                data = resp.read()
            if not data.startswith(b"\x89PNG"):
                last = f"{url}: not a PNG ({len(data)} bytes)"
                continue
            return dex_id, data, None
        except (urllib.error.URLError, OSError) as exc:  # includes timeouts
            last = f"{url}: {exc}"
    return dex_id, None, last


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--gen1", action="store_true",
                    help="use the Red/Blue sprites instead of the modern default art")
    ap.add_argument("--out", default="sprites-data.js", help="output JS file")
    ap.add_argument("--inline", metavar="HTML",
                    help="also write a self-contained copy of this HTML file")
    ap.add_argument("--workers", type=int, default=12, help="parallel downloads")
    ap.add_argument("--timeout", type=float, default=30.0, help="per-request timeout")
    args = ap.parse_args()

    path = PATHS["gen1" if args.gen1 else "default"]
    print(f"Fetching {COUNT} sprites from {path} ...", file=sys.stderr)

    sprites, failures = {}, []
    with futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
        jobs = [pool.submit(fetch, i, path, args.timeout) for i in range(1, COUNT + 1)]
        for done, job in enumerate(futures.as_completed(jobs), 1):
            dex_id, data, err = job.result()
            if data is None:
                failures.append(f"#{dex_id} {err}")
            else:
                sprites[dex_id] = ("data:image/png;base64,"
                                   + base64.b64encode(data).decode("ascii"))
            if done % 25 == 0 or done == COUNT:
                print(f"  {done}/{COUNT}", file=sys.stderr)

    if failures:
        print(f"\n{len(failures)} sprite(s) failed:", file=sys.stderr)
        for line in failures:
            print("  " + line, file=sys.stderr)
        if not sprites:
            return 1

    payload = json.dumps({str(k): sprites[k] for k in sorted(sprites)},
                         separators=(",", ":"))
    js = ("// Generated by bundle-sprites.py -- do not edit.\n"
          f"// {len(sprites)}/{COUNT} Gen 1 sprites ({path}) as base64 data URIs.\n"
          f"window.SPRITE_DATA = {payload};\n")

    out = pathlib.Path(args.out)
    out.write_text(js, encoding="utf-8")
    print(f"\nWrote {out} ({len(sprites)} sprites, {len(js)/1024:.0f} KB)", file=sys.stderr)

    if args.inline:
        src = pathlib.Path(args.inline)
        html = src.read_text(encoding="utf-8")
        if not MARKER.search(html):
            print(f"error: no <script src=\"sprites-data.js\"> tag found in {src}",
                  file=sys.stderr)
            return 1
        # An inline <script> cannot contain the literal "</script>"; the data
        # is pure base64 so this is belt-and-braces.
        tag = "<script>\n" + js.replace("</", "<\\/") + "</script>"
        dest = src.with_name(src.stem + "-bundled" + src.suffix)
        dest.write_text(MARKER.sub(lambda _: tag, html, count=1), encoding="utf-8")
        print(f"Wrote {dest} ({dest.stat().st_size/1024:.0f} KB, self-contained)",
              file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
